### ISSUE TITLE
How to not delete my static formulas?

### ISSUE THREAD

**Issue by NoSubstitute** [dwberry/Google-Apps-EDU-Admin#1]
Hi,Derek!
Regarding line 32.
Is there any possibility to clear data only in the columns into which I will pull new data (A-F, because we're pulling 6 fields of data), and not the G column where I keep my two formulas?

Preferably it should know how many columns contain data pulled by the script, and not actually know which column to not delete.

**Comment by NoSubstitute** [comment]
OMG! I meant **NOT** delete my formulas.

**Comment by dwberry** [comment]
Hey Kim.
I believe you could do this through the setActiveRanges method.
https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app#setactiverangerange
It will let you explicitly define the range in spreadsheet notion ie. A1:B2

**Comment by NoSubstitute** [comment]
Thanks!
So even a rule set to A1:F should work?
Since I don't know the number of rows beforehand, I can't give an exact
range.

>
